


server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservice_test
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  mvc:
    path match:
      matching-strategy: ant-path-matcher

application:
  name:Product_FC
